import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoryBlokProvider from "@/components/StoryBlokProvider";
import { initStoryblok } from "@/lib/storyblok";
import { getStoryblokApi } from "@storyblok/react/rsc";
import ServerComponent from "@/components/sb/ServerComponent";


const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = { title: "Create Next App", description: "Generated by create next app" };

export default async function RootLayout({ children }) {
  // ✅ init på serversidan
  initStoryblok();

  const api = getStoryblokApi();
  const { data } = await api.get("cdn/stories/config", {   // ← rättat: stories (inte stpries)
    version: process.env.NODE_ENV === "development" ? "draft" : "published",
    resolve_links: "url",
  });
  const config = data?.story?.content ?? {};
  const navigation = config.navigation ?? [];
  const footerLinks = config.footer ?? config.footer_links ?? [];

  return (
    <StoryBlokProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="border-b p-4">
            <nav className="container mx-auto flex gap-6">
             <div className="flex gap-6"> 
              {navigation.map((item) => (
                <ServerComponent blok={item} key={item._uid} />
              ))}
              </div>
            </nav>
          </header>

          <main>{children}</main>

          <footer className="border-t p-6 text-sm">
            <div className="container mx-auto flex gap-4 flex-wrap">
              {footerLinks.map((item) => (
                <ServerComponent blok={item} key={item._uid} />
              ))}
            </div>
          </footer>
        </body>
      </html>
    </StoryBlokProvider>
  );
}

